"""Build every exact-NURBS gallery piece (Wave J7) and regenerate GALLERY.md.

Runs each ``examples/n*_*.py`` piece in-process, collects its
:class:`NurbsPieceResult`, and writes ``examples/GALLERY.md`` — a thumbnail row
plus, per piece, the exact-NURBS feature it exercises and the ``nurbs.*`` API
calls it uses.

Usage:
    export CYBERCADKERNEL_DYLIB="$PWD/build-mac/libcybercadkernel.dylib"
    python3 examples/run_all_nurbs.py
"""

from __future__ import annotations

import importlib
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

# Ordered list of the NURBS gallery piece modules.
PIECES = [
    "n1_lofted_bracket",
    "n2_nsided_boss",
    "n3_filleted_freeform_boss",
    "n4_chamfer_vertex_blend",
    "n5_reverse_engineered_primitive",
    "n6_faired_scan_patch",
    "n7_variable_swept_handle",
    "n8_trim_boolean_pocket",
    "n9_revolved_rational",
]


def _gallery_md(results) -> str:
    lines = []
    lines.append("# CyberCadKernel — exact-NURBS example gallery (Wave J7)\n")
    lines.append(
        "Mechanical-piece examples that each exercise one exact-NURBS feature family "
        "through the `cybercadkernel.nurbs` Python API (the ergonomic layer over the "
        "additive `cc_nurbs_*` C facade) and render a validated PNG. These are a "
        "*consumer* gallery: no C ABI or Python package internals are modified.\n"
    )
    lines.append("## How to build\n")
    lines.append("```sh")
    lines.append("# Build the real-engine dylib with the numsci substrate on")
    lines.append("cmake -S . -B build-mac -DCMAKE_BUILD_TYPE=Release \\")
    lines.append("  -DCYBERCAD_MACOS_OCCT=ON -DCYBERCAD_HAS_NUMSCI=ON \\")
    lines.append("  -DCYBERCAD_NUMSCI_DIR=<build-numsci output> \\")
    lines.append("  -DCYBERCAD_NUMPP_DIR=<NumPP> -DCYBERCAD_SCIPP_DIR=<SciPP>")
    lines.append("cmake --build build-mac --target cybercadkernel")
    lines.append("")
    lines.append('export CYBERCADKERNEL_DYLIB="$PWD/build-mac/libcybercadkernel.dylib"')
    lines.append("python3 examples/run_all_nurbs.py     # or any examples/n*_*.py directly")
    lines.append("```\n")

    lines.append("## Display-tessellation caveat\n")
    lines.append(
        "`Surface.tessellate()` produces a **single-surface display mesh**. A single "
        "surface is **real exact geometry** (a full-turn revolved ring or the detected "
        "cylinder tessellates watertight). A piece assembled from **several** surfaces "
        "(a fillet band plus its host faces, the sub-patches of an N-sided fill or a "
        "vertex blend) is an honest **face-set** — shown together, *not* sewn into a "
        "watertight solid. Each piece below states which it is.\n"
    )

    # Thumbnail row.
    lines.append("## Thumbnails\n")
    row = []
    for r in results:
        if r.png_rel:
            row.append(
                f'<a href="#{r.name}"><img src="{r.png_rel}" width="150" alt="{r.title}"></a>'
            )
    lines.append("<p>" + " ".join(row) + "</p>\n")

    # Per-piece detail.
    lines.append("## Pieces\n")
    for i, r in enumerate(results, start=1):
        lines.append(f'### <a name="{r.name}"></a>{i}. {r.title}\n')
        if r.png_rel:
            lines.append(f'<img src="{r.png_rel}" width="360" alt="{r.title}">\n')
        lines.append(r.description + "\n")
        kind = (
            "single surface — **real geometry**"
            if r.is_single_surface
            else "**face-set** (display; not sewn watertight)"
        )
        lines.append(f"- **Feature exercised:** `{r.feature}`")
        lines.append(f"- **API calls:** " + ", ".join(f"`{c}`" for c in r.api_calls))
        lines.append(f"- **Geometry:** {kind} · {r.surface_count} surface(s)")
        sz = r.bbox_size
        lines.append(
            f"- **Display mesh:** {r.vertex_count} verts / {r.triangle_count} tris · "
            f"bbox {sz[0]:.1f} × {sz[1]:.1f} × {sz[2]:.1f}"
        )
        if r.png_rel:
            lines.append(f"- **Artifacts:** [PNG]({r.png_rel}) (rendered via {r.render_backend})")
        lines.append(f"- **Script:** [`{r.name}.py`]({r.name}.py)\n")

    lines.append("---\n")
    lines.append(
        "_Generated by `examples/run_all_nurbs.py`. The B-rep (`Kernel`/`Shape`) "
        "gallery is separate — see [`README.md`](README.md)._\n"
    )
    return "\n".join(lines)


def main() -> int:
    results = []
    failures = []
    for name in PIECES:
        mod = importlib.import_module(name)
        try:
            result = mod.run_and_report(mod.build)  # type: ignore[attr-defined]
            results.append(result)
            if not result.png_rel:
                failures.append((name, "no PNG produced"))
        except Exception as exc:  # a piece that cannot build is a reported failure
            print(f"[{name}] FAILED: {exc!r}")
            failures.append((name, repr(exc)))
        print()

    if results:
        md_path = os.path.join(_HERE, "GALLERY.md")
        with open(md_path, "w") as fh:
            fh.write(_gallery_md(results))
        print(f"wrote {md_path}  ({len(results)} pieces)")

    rendered = sum(1 for r in results if r.png_rel)
    print(f"\n== summary: {rendered}/{len(PIECES)} pieces rendered a validated PNG ==")
    for name, why in failures:
        print(f"   ! {name}: {why}")
    return 0 if rendered == len(PIECES) else 1


if __name__ == "__main__":
    raise SystemExit(main())
